### ISSUE TITLE
Fix Dockerfiles issues

### ISSUE THREAD

**Issue by jankeromnes** [jankeromnes/janitor#15]
There are several issues with project Dockerfiles that need to be fixed before the `beta` milestone, specifically:

- [x] Support `chrome_sandbox` for Chromium https://github.com/jankeromnes/dockerfiles/issues/4
- [x] Fix Chromium update (rebuild step) https://github.com/jankeromnes/dockerfiles/issues/5
- [x] Switch Chromium builds to GN https://github.com/jankeromnes/dockerfiles/issues/9
- [x] Fix Thunderbird build https://github.com/jankeromnes/dockerfiles/issues/7
- [x] Fix Servo crash in noVNC https://github.com/jankeromnes/dockerfiles/issues/8
- [x] Can't login to KDE in noVNC

**Comment by jankeromnes** [comment]
@rcatolino did you manage to make the noVNC session work with KDE? (By adding an empty password for `user`?)

**Comment by rcatolino** [comment]
I've made the changes to the kde dockerfile, but I can't test those changes without deleting my old kde workspace (so I guess this issue is dependent on https://github.com/jankeromnes/janitor/issues/10 as well).

**Comment by jankeromnes** [comment]
Thunderbird was fixed by https://github.com/jankeromnes/dockerfiles/commit/3041aa8f7cb1fafff09fe85f4c21a42ee5c00ac6.

**Comment by rcatolino** [comment]
The kde workspace is working now, the last issue was fixed by https://github.com/rcatolino/kdesrcbuild-docker/commit/7e2f25cd997baa586eb1a3ef53d2326ff6d59001

**Comment by jankeromnes** [comment]
All fixed! \o/
